apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{shop}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{shop}}
  template:
    metadata:
      labels:
        app: {{shop}}
    spec:
      containers:
      - name: {{shop}}
        image: {{digdigdigdig/shop:latest}}
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: shop-service
spec:
  selector:
    app: {{shop}}
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
